using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EA_MD5_hasher.NFS_ProStreet
{
    internal class Car_Presets
    {

        public static readonly Dictionary<string, string> RacerNames = new()
    {
        // Base Racers
        
{ "RACERNAME_000", "Alex Hutton" },
{ "RACERNAME_001", "Ken Burney" },
{ "RACERNAME_002", "Paul Ko" },
{ "RACERNAME_003", "Don Berry" },
{ "RACERNAME_004", "Pete Carter" },
{ "RACERNAME_005", "Eddy Spencer" },
{ "RACERNAME_006", "Bill Newman" },
{ "RACERNAME_007", "Will Jackson" },
{ "RACERNAME_008", "Carl Sanner" },
{ "RACERNAME_009", "Dale Bennett" },
{ "RACERNAME_010", "Felix Tang" },
{ "RACERNAME_011", "Pedro Wilson" },
{ "RACERNAME_012", "Wade Jackson" },
{ "RACERNAME_013", "Angelo Rowley" },
{ "RACERNAME_014", "Adrian Reed" },
{ "RACERNAME_015", "Christopher Jones" },
{ "RACERNAME_016", "Blaine Cook" },
{ "RACERNAME_017", "Chad Byers" },
{ "RACERNAME_018", "Travis Bratton" },
{ "RACERNAME_019", "Ron Chen" },
{ "RACERNAME_020", "Masahide Omura" },
{ "RACERNAME_021", "Kazutoshi Kawakami" },
{ "RACERNAME_022", "Ryoma Shibasawa" },
{ "RACERNAME_023", "Shinji Takasu" },
{ "RACERNAME_024", "Ukyo Ihara" },
{ "RACERNAME_025", "Masato Kihara" },
{ "RACERNAME_026", "Sadatake Ueshima" },
{ "RACERNAME_027", "Atshushi Muraguchi" },
{ "RACERNAME_028", "Shinji Mori" },
{ "RACERNAME_029", "Kaneko Hiroyori" },
{ "RACERNAME_030", "Tomonori Uetake" },
{ "RACERNAME_031", "Kohji Yamagata" },
{ "RACERNAME_032", "Kazu Yoshida" },
{ "RACERNAME_033", "Makoto Yoshizawa" },
{ "RACERNAME_034", "Yoshiaki Kawakami" },
{ "RACERNAME_035", "Conrad Miller" },
{ "RACERNAME_036", "Fred Watkins" },
{ "RACERNAME_037", "Diego Wolfe" },
{ "RACERNAME_038", "Marcel Porter" },
{ "RACERNAME_039", "Jonathan Evans" },
{ "RACERNAME_040", "Takuya Kawayama" },
{ "RACERNAME_041", "Satoshi Hosokaya" },
{ "RACERNAME_042", "Mitsuharu Tanaka" },
{ "RACERNAME_043", "Naoki Yoshihara" },
{ "RACERNAME_044", "Hiroaki Terasawa" },
{ "RACERNAME_045", "Munehiko Kawaguchi" },
{ "RACERNAME_046", "Mitsuhide Nakamura" },
{ "RACERNAME_047", "Yoshio Sato" },
{ "RACERNAME_048", "Charlie Heyman" },
{ "RACERNAME_049", "Colby Canham" },
{ "RACERNAME_050", "Brandon Tennant ^" },
{ "RACERNAME_051", "Perry Prescott" },
{ "RACERNAME_052", "Oliver Armitage" },
{ "RACERNAME_053", "Don Braun" },
{ "RACERNAME_054", "Seb Crawford" },
{ "RACERNAME_055", "Tyron Bryan" },
{ "RACERNAME_056", "Stuart Mitchell" },
{ "RACERNAME_057", "Kyle Easter" },
{ "RACERNAME_058", "Scott East" },
{ "RACERNAME_059", "Rory Taggart" },
{ "RACERNAME_060", "Mike Lineman" },
{ "RACERNAME_061", "Matt Pritchard" },
{ "RACERNAME_062", "Karl Losey" },
{ "RACERNAME_063", "Ben Haverman" },
{ "RACERNAME_064", "Filip Douglas" },
{ "RACERNAME_065", "Marcel Buddenseik" },
{ "RACERNAME_066", "Chet Higgens" },
{ "RACERNAME_067", "Klaus Steele" },
{ "RACERNAME_068", "Gustavo Demetrius" },
{ "RACERNAME_069", "Dominik Wilkins" },
{ "RACERNAME_070", "Charlie Gaskins" },
{ "RACERNAME_071", "Bill Tireman" },
{ "RACERNAME_072", "Al Gregg" },
{ "RACERNAME_073", "Rob Chase" },
{ "RACERNAME_074", "Bruno Hardy" },

// Booster Racers
{ "BOOST_RACERNAME_001", "Carey Hill" },
{ "BOOST_RACERNAME_002", "Dustin Elton" },
{ "BOOST_RACERNAME_003", "Josh Fairview" },
{ "BOOST_RACERNAME_004", "David Con" },
{ "BOOST_RACERNAME_005", "Manny Solemn" },
{ "BOOST_RACERNAME_006", "Konrad Mull" },
{ "BOOST_RACERNAME_007", "Victor Hesh" },
{ "BOOST_RACERNAME_008", "Clayton Mason" },
{ "BOOST_RACERNAME_009", "Nikki Swan" },
{ "BOOST_RACERNAME_010", "Jake Winston" },
{ "BOOST_RACERNAME_012", "Edward Hamilton" },
{ "BOOST_RACERNAME_014", "Gary Right" },
{ "BOOST_RACERNAME_016", "Vincent Strongarm" },
{ "BOOST_RACERNAME_018", "John Laurier" },
{ "BOOST_RACERNAME_019", "Jimmy Plant" },
{ "BOOST_RACERNAME_020", "Ashley Veer" },
{ "BOOST_RACERNAME_021", "Carl Money" },
{ "BOOST_RACERNAME_022", "Eduardo Williams" },

// Elite Racers
{ "ELITENAME_001", "Mamoru Arakawa" },
{ "ELITENAME_002", "Seiko Makiguchi" },
{ "ELITENAME_003", "Tsuneo Hamamoto" },
{ "ELITENAME_004", "Takeshi Tatsumi" },
{ "ELITENAME_005", "Ryota Iwahara" },
{ "ELITENAME_006", "Shiheru Mitani" },
{ "ELITENAME_007", "Takejiro Okuda" },
{ "ELITENAME_008", "Hide Okui" },
{ "ELITENAME_009", "Masao Hasekura" },
{ "ELITENAME_010", "Minoru Higashiyama" },
{ "ELITENAME_011", "Hitoshi Morie" },
{ "ELITENAME_012", "Nobu Sawayama" },
{ "ELITENAME_013", "Antoine Gaskins" },
{ "ELITENAME_014", "Tobias Sachenbacher" },
{ "ELITENAME_015", "Kelvin Coates" },
{ "ELITENAME_016", "Andreas Romanoff" },
{ "ELITENAME_017", "Armand Walker" },
{ "ELITENAME_018", "Ulrik Armstrong" },
{ "ELITENAME_019", "Rudolph Reese" },
{ "ELITENAME_020", "Tristan Christopher" },
{ "ELITENAME_021", "Derek Anderson" },
{ "ELITENAME_022", "Josh Mason" },
{ "ELITENAME_023", "Corey Digger" },
{ "ELITENAME_024", "Brad Adams" },
{ "ELITENAME_025", "Cole Smith" },
{ "ELITENAME_026", "Jimmy Sway" },
{ "ELITENAME_027", "Tony Smalls" },

// DDay Racers
{ "DDAY_OPP_01", "Eddie Cargo" },
{ "DDAY_OPP_02", "Benny Gold" },
{ "DDAY_OPP_03", "Samantha Cross" },
{ "DDAY_OPP_04", "Bill Vein" },
{ "DDAY_OPP_05", "Mark Mann" },
{ "DDAY_OPP_06", "Roger Sole" },
{ "DDAY_OPP_07", "Wilson Wong" },

// Drag Entourage
{ "DRAG_ENTOURAGE_1", "Bradley Hunter" },
{ "DRAG_ENTOURAGE_2", "Frank Book" },
{ "DRAG_ENTOURAGE_3", "Craig Wright" },

// Drift Entourage
{ "DRIFT_ENTOURAGE_1", "Yoshi Suzuki" },
{ "DRIFT_ENTOURAGE_2", "Tony Manilla" },
{ "DRIFT_ENTOURAGE_3", "Vinnie Gaul" },

// Grip Entourage
{ "GRIP_ENTOURAGE_1", "Rudy Chen" },
{ "GRIP_ENTOURAGE_2", "Gavin May" },
{ "GRIP_ENTOURAGE_3", "Henrik Dehn" },

// Kings
{ "Drag King", "Karol Monroe" },
{ "Drift King", "Aki Kimura" },
{ "Shadow King", "Ryo Watanabe" },
{ "Speed King", "Nate Denver" },
{ "Grip King",  "Ray Krieger" },

// Showdown Entourage
{ "SHOWDOWN_ENTOURAGE_1", "Joe Tackett" },
{ "SHOWDOWN_ENTOURAGE_2", "Takeshi Sato" },
{ "SHOWDOWN_ENTOURAGE_3", "Ivan Tarkovsky" },
{ "SHOWDOWN_ENTOURAGE_4", "Paul Trask" },

// Speed Entourage
{ "SC_ENTOURAGE_1", "Paulo Cruz" },
{ "SC_ENTOURAGE_2", "JP Laurent" },
{ "SC_ENTOURAGE_3", "Carlos Galliano" }
    };



        Dictionary<string, string> presetCarMap = new Dictionary<string, string>()
{
    // Temp / Challenge Presets
    { "ch_t3_inf_drag", "challenger71" },
    { "ch_t3_inf_drift", "nsx" },
    { "ch_t3_inf_grip", "caymans" },
    { "ch_t3_inf_grip2", "nsx" },
    { "p_ch_t1_nvd_drag", "cobaltss" },
    { "p_ch_t1_nvd_drag2", " civichb" },
    { "p_ch_t1_nvd_grip", "gti" },
    { "p_ch_t1_tx_drag", "gti" },
    { "p_ch_t1_tx_drift", "350z" },
    { "p_ch_t1_tx_grip", "gti" },
    { "p_ch_t1_tx_grip2", "350z" },
    { "p_ch_t1_willow_drag", "is350" },
    { "p_ch_t1_willow_drag2", "chevelle" },
    { "p_ch_t1_willow_drift", "chevelle" },
    { "p_ch_t1_willow_grip", "is350" },
    { "p_ch_t2_autop_drift", "gto" },
    { "p_ch_t2_autop_drift2", "g35" },
    { "p_ch_t2_autop_grip", "gto" },
    { "p_ch_t2_ce_autop_drift", "silvia" },
    { "p_ch_t2_ce_autop_grip", "silvia" },
    { "p_ch_t2_ce_autop_grip2", "solsticegxp" },
    { "p_ch_t2_eb_drift", "supra" },
    { "p_ch_t2_eb_grip", "bmwm3" },
    { "p_ch_t2_eb_sc", "bmwm3" },
    { "p_ch_t2_eb_sc2", "supra" },
    { "p_ch_t3_autob_drift", "viper" },
    { "p_ch_t3_autob_grip", "skyline" },
    { "p_ch_t3_autob_sc", "viper" },
    { "p_ch_t3_autob_sc2", "skyline" },
    { "p_ch_t3_nev_drag", "corvettez06" },
    { "p_ch_t3_nev_drift", "corvettez06" },
    { "p_ch_t3_nev_grip", "rs4" },
    { "p_ch_t3_nev_sc", "rs4" },
    { "p_ch_t3_nev_sc2", "corvettez06" },

    // Ad Sale / Promotional
    { "coke_gti", "gti" },
    { "energizer_viper", "viper" },

            // Bonus / Frontend Cars
    {"0x9b879916", "mazdaspeed3"},
    { "fe_drag_1_civichb", "civichb" },
    { "fe_drag_1_cobaltss", "cobaltss" },
    { "fe_drag_1_cuda", "cuda" },
    { "fe_drag_1_mustshlbyo", "mustangshlbyo" },
    { "fe_drag_2_charg69", "charger69" },
    { "fe_drag_2_eclipse", "eclipse" },
    { "fe_drag_2_evo09", "lancerevo9" },
    { "fe_drag_2_r32", "r32" },
    { "fe_drag_3_gti", "gti" },
    { "fe_drag_3_mustgt", "mustanggt" },
    { "fe_drag_3_skyline", "skyline" },
    { "fe_drag_3_wrx", "imprezawrxsti" },
    { "fe_drift_1_240sx", "240sx" },
    { "fe_drift_1_corolla", "corolla" },
    { "fe_drift_1_rx7", "rx7" },
    { "fe_drift_1_silvia", "silvia" },
    { "fe_drift_2_350z", "350z" },
    { "fe_drift_2_chevelle", "chevelle" },
    { "fe_drift_2_g35", "g35" },
    { "fe_drift_2_supra", "supra" },
    { "fe_drift_3_c6", "corvette" },
    { "fe_drift_3_challenger", "challenger71" },
    { "fe_drift_3_rx8", "rx8" },
    { "fe_drift_3_viper", "viper" },
    { "fe_grip_1_charger69", "charger69" },
    { "fe_grip_1_chevelle", "chevelle" },
    { "fe_grip_1_corolla", "corolla" },
    { "fe_grip_1_rx8", "rx8" },
    { "fe_grip_2_cosworth", "cosworth" },
    { "fe_grip_2_eclipse", "eclipse" },
    { "fe_grip_2_g35", "g35" },
    { "fe_grip_2_s3", "s3" },
    { "fe_grip_3_corvc6", "corvette" },
    { "fe_grip_3_gto", "gto" },
    { "fe_grip_3_murc640", "murcielago640" },
    { "fe_grip_3_supra", "supra" },
    { "fe_sc_1_chall71", "challenger71" },
    { "fe_sc_1_cosworth", "cosworth" },
    { "fe_sc_1_r32", "r32" },
    { "fe_sc_1_s3", "s3" },
    { "fe_sc_2_elise", "elise" },
    { "fe_sc_2_rx8", "rx8" },
    { "fe_sc_2_silvia", "silvia" },
    { "fe_sc_3_camaross", "camaro" },
    { "fe_sc_3_caymans", "caymans" },
    { "fe_sc_3_fordgt", "fordgt" },
    { "fe_sc_3_s4", "s4" },

    // Booster Opponents - Drag
    { "b_opp_1_drag", "dlcbp_challengern" },
    { "b_opp_10_drag", "ttn" },
    { "b_opp_12_drag", "dlcbp_r8prod" },
    { "b_opp_14_drag", "dlcbp_s2000" },
    { "b_opp_16_drag", "dlcbp_gallardos" },
    { "b_opp_18_drag", "dlcbp_sl65" },
    { "b_opp_19_drag", "dlcbp_db9" },
    { "b_opp_2_drag", "dlcbp_delta" },
    { "b_opp_20_drag", "dlcbp_997gt3" },
    { "b_opp_21_drag", "dlcbp_997gt3rs" },
    { "b_opp_22_drag", "dlcbp_carreragt" },
    { "b_opp_3_drag", "dlcbp_roadrunner" },
    { "b_opp_4_drag", "dlcbp_leoncupra" },
    { "b_opp_5_drag", "dlcbp_challengern" },
    { "b_opp_6_drag", "dlcbp_delta" },
    { "b_opp_7_drag", "dlcbp_roadrunner" },
    { "b_opp_8_drag", "dlcbp_leoncupra" },
    { "b_opp_9_drag", "mustang03" },

    // Booster Opponents - Drift
    { "b_opp_1_drift", "dlcbp_challengern" },
    { "b_opp_10_drift", " bmwmz4" },
    { "b_opp_12_drift", "dlcbp_challengern" },
    { "b_opp_14_drift", "dlcbp_s2000" },
    { "b_opp_16_drift", "dlcbp_s2000" },
    { "b_opp_18_drift", "dlcbp_sl65" },
    { "b_opp_19_drift", "dlcbp_db9" },
    { "b_opp_2_drift", "nsx" },
    { "b_opp_20_drift", "dlcbp_997gt3" },
    { "b_opp_21_drift", "dlcbp_997gt3rs" },
    { "b_opp_22_drift", "dlcbp_carreragt" },
    { "b_opp_3_drift", "dlcbp_roadrunner" },
    { "b_opp_4_drift", "solsticegxp" },
    { "b_opp_5_drift", "dlcbp_challengern" },
    { "b_opp_6_drift", "is350" },
    { "b_opp_7_drift", "dlcbp_roadrunner" },
    { "b_opp_8_drift", "997gt2" },
    { "b_opp_9_drift", "mustang03" },

    // Booster Opponents - Grip
    { "b_opp_1_grip", "dlcbp_challengern" },
    { "b_opp_10_grip", "ttn" },
    { "b_opp_12_grip", "dlcbp_r8prod" },
    { "b_opp_14_grip", "dlcbp_s2000" },
    { "b_opp_16_grip", "dlcbp_gallardos" },
    { "b_opp_18_grip", "dlcbp_sl65" },
    { "b_opp_19_grip", "dlcbp_db9" },
    { "b_opp_2_grip", "dlcbp_delta" },
    { "b_opp_20_grip", "dlcbp_997gt3" },
    { "b_opp_21_grip", "dlcbp_997gt3rs" },
    { "b_opp_22_grip", "dlcbp_carreragt" },
    { "b_opp_3_grip", "dlcbp_roadrunner" },
    { "b_opp_4_grip", "dlcbp_leoncupra" },
    { "b_opp_5_grip", "dlcbp_challengern" },
    { "b_opp_6_grip", "dlcbp_delta" },
    { "b_opp_7_grip", "dlcbp_roadrunner" },
    { "b_opp_8_grip", "dlcbp_leoncupra" },
    { "b_opp_9_grip", "mustang03" },

    // Booster Opponents - Speed Challenge
    { "b_opp_1_sc", "dlcbp_challengern" },
    { "b_opp_10_sc", "ttn" },
    { "b_opp_12_sc", "dlcbp_r8prod" },
    { "b_opp_14_sc", "dlcbp_s2000" },
    { "b_opp_16_sc", "dlcbp_gallardos" },
    { "b_opp_18_sc", "dlcbp_sl65" },
    { "b_opp_19_sc", "dlcbp_db9" },
    { "b_opp_2_sc", "dlcbp_delta" },
    { "b_opp_20_sc", "dlcbp_997gt3" },
    { "b_opp_21_sc", "dlcbp_997gt3rs" },
    { "b_opp_22_sc", "dlcbp_carreragt" },
    { "b_opp_3_sc", "dlcbp_roadrunner" },
    { "b_opp_4_sc", "dlcbp_leoncupra" },
    { "b_opp_5_sc", "dlcbp_challengern" },
    { "b_opp_6_sc", "dlcbp_delta" },
    { "b_opp_7_sc", "dlcbp_roadrunner" },
    { "b_opp_8_sc", "dlcbp_leoncupra" },
    { "b_opp_9_sc", "mustang03" },

    // Commercial / Promotional Cars
    { "commercial_ae86", "corolla" },
    { "commercial_camaro", "camaro" },
    { "commercial_cuda", "cuda" },
    { "commercial_e92", "bmwm3e92" },
    { "commercial_evo", "lancerevo9" },
    { "commercial_fordgt", "fordgt" },
    { "commercial_gt2", "997gt2" },
    { "commercial_mustang", "mustanggt" },
    { "commercial_mustang_old", "mustanggt" },
    { "commercial_proto", "gtrproto" },
    { "commercial_rx7", "rx7" },
    { "commercial_s15", "silvia" },
    { "commercial_s4", "s4" },
    { "commercial_wrx", "imprezawrxsti" },

    // Debug / Dev Presets
    { "jacques_mobile", "rx7" },
    { "jacques_mobile_drag", "0x195b4ae8" },
    { "jacques_mobile_grip", "350z" },
    { "jacques_mobile_speed", "350z" },

    // Entourage Drag
    { "drag_entourage_1_drag", "chevelle" },
    { "drag_entourage_2_drag", "challenger71" },
    { "drag_entourage_3_drag", "gto" },
    { "showdown_entourage_1_drag", "civichb" },
    { "showdown_entourage_2_drag", "silvia" },
    { "showdown_entourage_3_drag", "lancerevo9" },
    { "showdown_entourage_4_drag", "skyline" },

    // Entourage Drift
    { "drift_entourage_1_drift", "350z" },
    { "drift_entourage_2_drift", "camaro" },
    { "drift_entourage_3_drift", "corolla" },
    { "showdown_entourage_2_drift", "silvia" },

    // Entourage Grip
    { "grip_entourage_1_grip", "997tt" },
    { "grip_entourage_2_grip", "cosworth" },
    { "grip_entourage_3_grip", "s4" },
    { "showdown_entourage_1_grip", "civichb" },
    { "showdown_entourage_2_grip", "silvia" },
    { "showdown_entourage_3_grip", "lancerevo9" },
    { "showdown_entourage_4_grip", "skyline" },

    // Entourage Speed Challenge
    { "sc_entourage_1_sc", "corvettez06" },
    { "sc_entourage_2_sc", "zonda" },
    { "sc_entourage_3_sc", "supra" },
    { "showdown_entourage_1_sc", "civichb" },
    { "showdown_entourage_2_sc", "silvia" },
    { "showdown_entourage_3_sc", "lancerevo9" },
    { "showdown_entourage_4_sc", "skyline" },

    // Boss / King Cars
    { "drag_king", "mustanggt" },
    { "drift_king", "rx7" },
    { "grip_king", "bmwm3e92" },
    { "sc_king", "gto65" },
    { "showdown_king_final_drag", "showdown_king" },
    { "showdown_king_final_drift", "showdown_king" },
    { "showdown_king_final_grip", "lancerevox" },
    { "showdown_king_final_sc", "lancerevox" },
    { "showdown_king_playable", "lancerevox" },

    // Challenge Mode - Drag
    { "ch_t1_ptl_drag_civichb", "civichb" },
    { "ch_t1_ptl_drag_mustgt", "cobaltss" },
    { "ch_t1_tx_drag_gti", "gti" },
    { "ch_t1_willow_drag_chevelle", "chevelle" },
    { "ch_t3_infineon_drag_cayman", "challenger71" },
    { "ch_t3_nevada_drag_z06", "corvettez06" },

    // Challenge Mode - Drift
    { "ch_t1_tx_drift_350z", "350z" },
    { "ch_t1_willow_drift_chevelle", "chevelle" },
    { "ch_t1_willow_drift_is350", "is350" },
    { "ch_t2_autop_drift_s15", "silvia" },
    { "ch_t2_autop_drift_solstice", "solsticegxp" },
    { "ch_t2_ebisu_drift_supra", "supra" },
    { "ch_t2_mond_drift_g35", "g35" },
    { "ch_t2_mond_drift_gto", "gto" },
    { "ch_t3_autob_drift_viper", "viper" },
    { "ch_t3_infineon_drift_nsx", "nsx" },
    { "ch_t3_nevada_drift_z06", "corvettez06" },

    // Challenge Mode - Grip
    { "ch_t1_ptl_grip_civichb", "gti" },
    { "ch_t1_tx_grip_350z", "350z" },
    { "ch_t1_tx_grip_gti", "gti" },
    { "ch_t1_willow_grip_is350", "is350" },
    { "ch_t2_autop_grip_s15", "silvia" },
    { "ch_t2_ebisu_grip_bmwm3", "bmwm3" },
    { "ch_t2_mond_grip_gto", "gto" },
    { "ch_t3_autob_grip_skyline", "skyline" },
    { "ch_t3_infineon_grip_cayman", "caymans" },
    { "ch_t3_infineon_grip_nsx", "nsx" },
    { "ch_t3_nevada_grip_rs4", "rs4" },

    // Challenge Mode - Speed Challenge
    { "ch_t2_ebisu_sc_bmwm3", "bmwm3" },
    { "ch_t2_ebisu_sc_supra", "supra" },
    { "ch_t3_autob_sc_skyline", "skyline" },
    { "ch_t3_autob_sc_viper", "viper" },
    { "ch_t3_nevada_sc_rs4", "rs4" },
    { "ch_t3_nevada_sc_z06", "corvettez06" },

    // D-Day Event
    { "dday_opp_1_grip", "civichb" },
    { "dday_opp_2_grip", "corolla" },
    { "dday_opp_3_grip", "240sx" },
    { "dday_opp_4_grip", "civichb" },
    { "dday_opp_5_grip", "240sx" },
    { "dday_opp_6_grip", "corolla" },
    { "dday_opp_7_grip", "civichb" },

    // Elite Opponents - Drag
    { "elite_opp_1_drag", "Elite Opponent 1 (Drag)" },
    { "elite_opp_11_drag", "Elite Opponent 11 (Drag)" },
    { "elite_opp_12_drag", "Elite Opponent 12 (Drag)" },
    { "elite_opp_13_drag", "Elite Opponent 13 (Drag)" },
    { "elite_opp_14_drag", "Elite Opponent 14 (Drag)" },
    { "elite_opp_15_drag", "Elite Opponent 15 (Drag)" },
    { "elite_opp_16_drag", "Elite Opponent 16 (Drag)" },
    { "elite_opp_17_drag", "Elite Opponent 17 (Drag)" },
    { "elite_opp_18_drag", "Elite Opponent 18 (Drag)" },
    { "elite_opp_19_drag", "Elite Opponent 19 (Drag)" },
    { "elite_opp_2_drag", "Elite Opponent 2 (Drag)" },
    { "elite_opp_20_drag", "Elite Opponent 20 (Drag)" },
    { "elite_opp_21_drag", "Elite Opponent 21 (Drag)" },
    { "elite_opp_22_drag", "Elite Opponent 22 (Drag)" },
    { "elite_opp_23_drag", "Elite Opponent 23 (Drag)" },
    { "elite_opp_24_drag", "Elite Opponent 24 (Drag)" },
    { "elite_opp_25_drag", "Elite Opponent 25 (Drag)" },
    { "elite_opp_26_drag", "Elite Opponent 26 (Drag)" },
    { "elite_opp_3_drag", "Elite Opponent 3 (Drag)" },
    { "elite_opp_4_drag", "Elite Opponent 4 (Drag)" },
    { "elite_opp_5_drag", "Elite Opponent 5 (Drag)" },

    // Elite Opponents - Drift
    { "elite_opp_1_drift", "Elite Opponent 1 (Drift)" },
    { "elite_opp_11_drift", "Elite Opponent 11 (Drift)" },
    { "elite_opp_12_drift", "Elite Opponent 12 (Drift)" },
    { "elite_opp_13_drift", "Elite Opponent 13 (Drift)" },
    { "elite_opp_14_drift", "Elite Opponent 14 (Drift)" },
    { "elite_opp_15_drift", "Elite Opponent 15 (Drift)" },
    { "elite_opp_16_drift", "Elite Opponent 16 (Drift)" },
    { "elite_opp_17_drift", "Elite Opponent 17 (Drift)" },
    { "elite_opp_18_drift", "Elite Opponent 18 (Drift)" },
    { "elite_opp_19_drift", "Elite Opponent 19 (Drift)" },
    { "elite_opp_2_drift", "Elite Opponent 2 (Drift)" },
    { "elite_opp_20_drift", "Elite Opponent 20 (Drift)" },
    { "elite_opp_3_drift", "Elite Opponent 3 (Drift)" },
    { "elite_opp_4_drift", "Elite Opponent 4 (Drift)" },
    { "elite_opp_5_drift", "Elite Opponent 5 (Drift)" },

    // Elite Opponents - Grip
    { "elite_opp_1_grip", "Elite Opponent 1 (Grip)" },
    { "elite_opp_11_grip", "Elite Opponent 11 (Grip)" },
    { "elite_opp_12_grip", "Elite Opponent 12 (Grip)" },
    { "elite_opp_13_grip", "Elite Opponent 13 (Grip)" },
    { "elite_opp_14_grip", "Elite Opponent 14 (Grip)" },
    { "elite_opp_15_grip", "Elite Opponent 15 (Grip)" },
    { "elite_opp_16_grip", "Elite Opponent 16 (Grip)" },
    { "elite_opp_17_grip", "Elite Opponent 17 (Grip)" },
    { "elite_opp_18_grip", "Elite Opponent 18 (Grip)" },
    { "elite_opp_19_grip", "Elite Opponent 19 (Grip)" },
    { "elite_opp_2_grip", "Elite Opponent 2 (Grip)" },
    { "elite_opp_20_grip", "Elite Opponent 20 (Grip)" },
    { "elite_opp_27_grip", "Elite Opponent 27 (Grip)" },
    { "elite_opp_3_grip", "Elite Opponent 3 (Grip)" },
    { "elite_opp_4_grip", "Elite Opponent 4 (Grip)" },
    { "elite_opp_5_grip", "Elite Opponent 5 (Grip)" },

    // Elite Opponents - Speed Challenge
    { "elite_opp_14_sc", "Elite Opponent 14 (Speed Challenge)" },
    { "elite_opp_15_sc", "Elite Opponent 15 (Speed Challenge)" },
    { "elite_opp_16_sc", "Elite Opponent 16 (Speed Challenge)" },
    { "elite_opp_17_sc", "Elite Opponent 17 (Speed Challenge)" },
    { "elite_opp_18_sc", "Elite Opponent 18 (Speed Challenge)" },
    { "elite_opp_19_sc", "Elite Opponent 19 (Speed Challenge)" },
    { "elite_opp_2_sc", "Elite Opponent 2 (Speed Challenge)" },
    { "elite_opp_20_sc", "Elite Opponent 20 (Speed Challenge)" },
    { "elite_opp_3_sc", "Elite Opponent 3 (Speed Challenge)" },
    { "elite_opp_4_sc", "Elite Opponent 4 (Speed Challenge)" },
    { "elite_opp_5_sc", "Elite Opponent 5 (Speed Challenge)" },

    // HD / Race Day Opponents - Drag
    { "hd_opp_1_drag", "Race Day Opponent 1 (Drag)" },
    { "hd_opp_10_drag", "Race Day Opponent 10 (Drag)" },
    { "hd_opp_11_drag", "Race Day Opponent 11 (Drag)" },
    { "hd_opp_12_drag", "Race Day Opponent 12 (Drag)" },
    { "hd_opp_13_drag", "Race Day Opponent 13 (Drag)" },
    { "hd_opp_14_drag", "Race Day Opponent 14 (Drag)" },
    { "hd_opp_15_drag", "Race Day Opponent 15 (Drag)" },
    { "hd_opp_2_drag", "Race Day Opponent 2 (Drag)" },
    { "hd_opp_3_drag", "Race Day Opponent 3 (Drag)" },
    { "hd_opp_4_drag", "Race Day Opponent 4 (Drag)" },
    { "hd_opp_5_drag", "Race Day Opponent 5 (Drag)" },
    { "hd_opp_6_drag", "Race Day Opponent 6 (Drag)" },
    { "hd_opp_7_drag", "Race Day Opponent 7 (Drag)" },
    { "hd_opp_8_drag", "Race Day Opponent 8 (Drag)" },
    { "hd_opp_9_drag", "Race Day Opponent 9 (Drag)" },

    // HD / Race Day Opponents - Drift
    { "hd_opp_1_drift", "Race Day Opponent 1 (Drift)" },
    { "hd_opp_10_drift", "Race Day Opponent 10 (Drift)" },
    { "hd_opp_11_drift", "Race Day Opponent 11 (Drift)" },
    { "hd_opp_12_drift", "Race Day Opponent 12 (Drift)" },
    { "hd_opp_13_drift", "Race Day Opponent 13 (Drift)" },
    { "hd_opp_14_drift", "Race Day Opponent 14 (Drift)" },
    { "hd_opp_15_drift", "Race Day Opponent 15 (Drift)" },
    { "hd_opp_2_drift", "Race Day Opponent 2 (Drift)" },
    { "hd_opp_3_drift", "Race Day Opponent 3 (Drift)" },
    { "hd_opp_4_drift", "Race Day Opponent 4 (Drift)" },
    { "hd_opp_5_drift", "Race Day Opponent 5 (Drift)" },
    { "hd_opp_6_drift", "Race Day Opponent 6 (Drift)" },
    { "hd_opp_7_drift", "Race Day Opponent 7 (Drift)" },
    { "hd_opp_8_drift", "Race Day Opponent 8 (Drift)" },
    { "hd_opp_9_drift", "Race Day Opponent 9 (Drift)" },

    // HD / Race Day Opponents - Grip
    { "hd_opp_1_grip", "Race Day Opponent 1 (Grip)" },
    { "hd_opp_10_grip", "Race Day Opponent 10 (Grip)" },
    { "hd_opp_11_grip", "Race Day Opponent 11 (Grip)" },
    { "hd_opp_12_grip", "Race Day Opponent 12 (Grip)" },
    { "hd_opp_13_grip", "Race Day Opponent 13 (Grip)" },
    { "hd_opp_14_grip", "Race Day Opponent 14 (Grip)" },
    { "hd_opp_15_grip", "Race Day Opponent 15 (Grip)" },
    { "hd_opp_2_grip", "Race Day Opponent 2 (Grip)" },
    { "hd_opp_3_grip", "Race Day Opponent 3 (Grip)" },
    { "hd_opp_4_grip", "Race Day Opponent 4 (Grip)" },
    { "hd_opp_5_grip", "Race Day Opponent 5 (Grip)" },
    { "hd_opp_6_grip", "Race Day Opponent 6 (Grip)" },
    { "hd_opp_7_grip", "Race Day Opponent 7 (Grip)" },
    { "hd_opp_8_grip", "Race Day Opponent 8 (Grip)" },
    { "hd_opp_9_grip", "Race Day Opponent 9 (Grip)" },

    // HD / Race Day Opponents - Speed Challenge
    { "hd_opp_1_sc", "Race Day Opponent 1 (Speed Challenge)" },
    { "hd_opp_10_sc", "Race Day Opponent 10 (Speed Challenge)" },
    { "hd_opp_11_sc", "Race Day Opponent 11 (Speed Challenge)" },
    { "hd_opp_12_sc", "Race Day Opponent 12 (Speed Challenge)" },
    { "hd_opp_13_sc", "Race Day Opponent 13 (Speed Challenge)" },
    { "hd_opp_14_sc", "Race Day Opponent 14 (Speed Challenge)" },
    { "hd_opp_15_sc", "Race Day Opponent 15 (Speed Challenge)" },
    { "hd_opp_2_sc", "Race Day Opponent 2 (Speed Challenge)" },
    { "hd_opp_3_sc", "Race Day Opponent 3 (Speed Challenge)" },
    { "hd_opp_4_sc", "Race Day Opponent 4 (Speed Challenge)" },
    { "hd_opp_5_sc", "Race Day Opponent 5 (Speed Challenge)" },
    { "hd_opp_6_sc", "Race Day Opponent 6 (Speed Challenge)" },
    { "hd_opp_7_sc", "Race Day Opponent 7 (Speed Challenge)" },
    { "hd_opp_8_sc", "Race Day Opponent 8 (Speed Challenge)" },
    { "hd_opp_9_sc", "Race Day Opponent 9 (Speed Challenge)" },

    // Generic Opponents - Drag
    { "opp_0_drag", "Standard Opponent 0 (Drag)" },
    { "opp_1_drag", "Standard Opponent 1 (Drag)" },
    { "opp_10_drag", "Standard Opponent 10 (Drag)" },
    { "opp_11_drag", "Standard Opponent 11 (Drag)" },
    { "opp_12_drag", "Standard Opponent 12 (Drag)" },
    { "opp_13_drag", "Standard Opponent 13 (Drag)" },
    { "opp_14_drag", "Standard Opponent 14 (Drag)" },
    { "opp_2_drag", "Standard Opponent 2 (Drag)" },
    { "opp_20_drag", "Standard Opponent 20 (Drag)" },
    { "opp_21_drag", "Standard Opponent 21 (Drag)" },
    { "opp_22_drag", "Standard Opponent 22 (Drag)" },
    { "opp_23_drag", "Standard Opponent 23 (Drag)" },
    { "opp_24_drag", "Standard Opponent 24 (Drag)" },
    { "opp_25_drag", "Standard Opponent 25 (Drag)" },
    { "opp_26_drag", "Standard Opponent 26 (Drag)" },
    { "opp_27_drag", "Standard Opponent 27 (Drag)" },
    { "opp_28_drag", "Standard Opponent 28 (Drag)" },
    { "opp_29_drag", "Standard Opponent 29 (Drag)" },
    { "opp_3_drag", "Standard Opponent 3 (Drag)" },
    { "opp_30_drag", "Standard Opponent 30 (Drag)" },
    { "opp_31_drag", "Standard Opponent 31 (Drag)" },
    { "opp_32_drag", "Standard Opponent 32 (Drag)" },
    { "opp_33_drag", "Standard Opponent 33 (Drag)" },
    { "opp_34_drag", "Standard Opponent 34 (Drag)" },
    { "opp_4_drag", "Standard Opponent 4 (Drag)" },
    { "opp_41_drag", "Standard Opponent 41 (Drag)" },
    { "opp_42_drag", "Standard Opponent 42 (Drag)" },
    { "opp_43_drag", "Standard Opponent 43 (Drag)" },
    { "opp_44_drag", "Standard Opponent 44 (Drag)" },
    { "opp_45_drag", "Standard Opponent 45 (Drag)" },
    { "opp_46_drag", "Standard Opponent 46 (Drag)" },
    { "opp_47_drag", "Standard Opponent 47 (Drag)" },
    { "opp_48_drag", "Standard Opponent 48 (Drag)" },
    { "opp_49_drag", "Standard Opponent 49 (Drag)" },
    { "opp_5_drag", "Standard Opponent 5 (Drag)" },
    { "opp_50_drag", "Standard Opponent 50 (Drag)" },
    { "opp_51_drag", "Standard Opponent 51 (Drag)" },
    { "opp_52_drag", "Standard Opponent 52 (Drag)" },
    { "opp_53_drag", "Standard Opponent 53 (Drag)" },
    { "opp_54_drag", "Standard Opponent 54 (Drag)" },
    { "opp_6_drag", "Standard Opponent 6 (Drag)" },
    { "opp_7_drag", "Standard Opponent 7 (Drag)" },
    { "opp_8_drag", "Standard Opponent 8 (Drag)" },
    { "opp_9_drag", "Standard Opponent 9 (Drag)" },

    // Generic Opponents - Drift
    { "opp_0_drift", "Standard Opponent 0 (Drift)" },
    { "opp_1_drift", "Standard Opponent 1 (Drift)" },
    { "opp_10_drift", "Standard Opponent 10 (Drift)" },
    { "opp_11_drift", "Standard Opponent 11 (Drift)" },
    { "opp_12_drift", "Standard Opponent 12 (Drift)" },
    { "opp_13_drift", "Standard Opponent 13 (Drift)" },
    { "opp_14_drift", "Standard Opponent 14 (Drift)" },
    { "opp_2_drift", "Standard Opponent 2 (Drift)" },
    { "opp_20_drift", "Standard Opponent 20 (Drift)" },
    { "opp_21_drift", "Standard Opponent 21 (Drift)" },
    { "opp_22_drift", "Standard Opponent 22 (Drift)" },
    { "opp_23_drift", "Standard Opponent 23 (Drift)" },
    { "opp_24_drift", "Standard Opponent 24 (Drift)" },
    { "opp_25_drift", "Standard Opponent 25 (Drift)" },
    { "opp_26_drift", "Standard Opponent 26 (Drift)" },
    { "opp_27_drift", "Standard Opponent 27 (Drift)" },
    { "opp_28_drift", "Standard Opponent 28 (Drift)" },
    { "opp_29_drift", "Standard Opponent 29 (Drift)" },
    { "opp_3_drift", "Standard Opponent 3 (Drift)" },
    { "opp_30_drift", "Standard Opponent 30 (Drift)" },
    { "opp_31_drift", "Standard Opponent 31 (Drift)" },
    { "opp_32_drift", "Standard Opponent 32 (Drift)" },
    { "opp_33_drift", "Standard Opponent 33 (Drift)" },
    { "opp_34_drift", "Standard Opponent 34 (Drift)" },
    { "opp_4_drift", "Standard Opponent 4 (Drift)" },
    { "opp_41_drift", "Standard Opponent 41 (Drift)" },
    { "opp_42_drift", "Standard Opponent 42 (Drift)" },
    { "opp_43_drift", "Standard Opponent 43 (Drift)" },
    { "opp_44_drift", "Standard Opponent 44 (Drift)" },
    { "opp_45_drift", "Standard Opponent 45 (Drift)" },
    { "opp_46_drift", "Standard Opponent 46 (Drift)" },
    { "opp_47_drift", "Standard Opponent 47 (Drift)" },
    { "opp_48_drift", "Standard Opponent 48 (Drift)" },
    { "opp_49_drift", "Standard Opponent 49 (Drift)" },
    { "opp_5_drift", "Standard Opponent 5 (Drift)" },
    { "opp_50_drift", "Standard Opponent 50 (Drift)" },
    { "opp_51_drift", "Standard Opponent 51 (Drift)" },
    { "opp_52_drift", "Standard Opponent 52 (Drift)" },
    { "opp_53_drift", "Standard Opponent 53 (Drift)" },
    { "opp_54_drift", "Standard Opponent 54 (Drift)" },
    { "opp_6_drift", "Standard Opponent 6 (Drift)" },
    { "opp_7_drift", "Standard Opponent 7 (Drift)" },
    { "opp_8_drift", "Standard Opponent 8 (Drift)" },
    { "opp_9_drift", "Standard Opponent 9 (Drift)" },

    // Generic Opponents - Grip
    { "opp_0_grip", "Standard Opponent 0 (Grip)" },
    { "opp_1_grip", "Standard Opponent 1 (Grip)" },
    { "opp_10_grip", "Standard Opponent 10 (Grip)" },
    { "opp_11_grip", "Standard Opponent 11 (Grip)" },
    { "opp_12_grip", "Standard Opponent 12 (Grip)" },
    { "opp_13_grip", "Standard Opponent 13 (Grip)" },
    { "opp_14_grip", "Standard Opponent 14 (Grip)" },
    { "opp_2_grip", "Standard Opponent 2 (Grip)" },
    { "opp_20_grip", "Standard Opponent 20 (Grip)" },
    { "opp_21_grip", "Standard Opponent 21 (Grip)" },
    { "opp_22_grip", "Standard Opponent 22 (Grip)" },
    { "opp_23_grip", "Standard Opponent 23 (Grip)" },
    { "opp_24_grip", "Standard Opponent 24 (Grip)" },
    { "opp_25_grip", "Standard Opponent 25 (Grip)" },
    { "opp_26_grip", "Standard Opponent 26 (Grip)" },
    { "opp_27_grip", "Standard Opponent 27 (Grip)" },
    { "opp_28_grip", "Standard Opponent 28 (Grip)" },
    { "opp_29_grip", "Standard Opponent 29 (Grip)" },
    { "opp_3_grip", "Standard Opponent 3 (Grip)" },
    { "opp_30_grip", "Standard Opponent 30 (Grip)" },
    { "opp_31_grip", "Standard Opponent 31 (Grip)" },
    { "opp_32_grip", "Standard Opponent 32 (Grip)" },
    { "opp_33_grip", "Standard Opponent 33 (Grip)" },
    { "opp_34_grip", "Standard Opponent 34 (Grip)" },
    { "opp_4_grip", "Standard Opponent 4 (Grip)" },
    { "opp_41_grip", "Standard Opponent 41 (Grip)" },
    { "opp_42_grip", "Standard Opponent 42 (Grip)" },
    { "opp_43_grip", "Standard Opponent 43 (Grip)" },
    { "opp_44_grip", "Standard Opponent 44 (Grip)" },
    { "opp_45_grip", "Standard Opponent 45 (Grip)" },
    { "opp_46_grip", "Standard Opponent 46 (Grip)" },
    { "opp_47_grip", "Standard Opponent 47 (Grip)" },
    { "opp_48_grip", "Standard Opponent 48 (Grip)" },
    { "opp_49_grip", "Standard Opponent 49 (Grip)" },
    { "opp_5_grip", "Standard Opponent 5 (Grip)" },
    { "opp_50_grip", "Standard Opponent 50 (Grip)" },
    { "opp_51_grip", "Standard Opponent 51 (Grip)" },
    { "opp_52_grip", "Standard Opponent 52 (Grip)" },
    { "opp_53_grip", "Standard Opponent 53 (Grip)" },
    { "opp_54_grip", "Standard Opponent 54 (Grip)" },
    { "opp_6_grip", "Standard Opponent 6 (Grip)" },
    { "opp_7_grip", "Standard Opponent 7 (Grip)" },
    { "opp_8_grip", "Standard Opponent 8 (Grip)" },
    { "opp_9_grip", "Standard Opponent 9 (Grip)" },

    // Generic Opponents - Speed Challenge
    { "opp_0_sc", "Standard Opponent 0 (Speed Challenge)" },
    { "opp_1_sc", "Standard Opponent 1 (Speed Challenge)" },
    { "opp_10_sc", "Standard Opponent 10 (Speed Challenge)" },
    { "opp_11_sc", "Standard Opponent 11 (Speed Challenge)" },
    { "opp_12_sc", "Standard Opponent 12 (Speed Challenge)" },
    { "opp_13_sc", "Standard Opponent 13 (Speed Challenge)" },
    { "opp_14_sc", "Standard Opponent 14 (Speed Challenge)" },
    { "opp_2_sc", "Standard Opponent 2 (Speed Challenge)" },
    { "opp_20_sc", "Standard Opponent 20 (Speed Challenge)" },
    { "opp_21_sc", "Standard Opponent 21 (Speed Challenge)" },
    { "opp_22_sc", "Standard Opponent 22 (Speed Challenge)" },
    { "opp_23_sc", "Standard Opponent 23 (Speed Challenge)" },
    { "opp_24_sc", "Standard Opponent 24 (Speed Challenge)" },
    { "opp_25_sc", "Standard Opponent 25 (Speed Challenge)" },
    { "opp_26_sc", "Standard Opponent 26 (Speed Challenge)" },
    { "opp_27_sc", "Standard Opponent 27 (Speed Challenge)" },
    { "opp_28_sc", "Standard Opponent 28 (Speed Challenge)" },
    { "opp_29_sc", "Standard Opponent 29 (Speed Challenge)" },
    { "opp_3_sc", "Standard Opponent 3 (Speed Challenge)" },
    { "opp_30_sc", "Standard Opponent 30 (Speed Challenge)" },
    { "opp_31_sc", "Standard Opponent 31 (Speed Challenge)" },
    { "opp_32_sc", "Standard Opponent 32 (Speed Challenge)" },
    { "opp_33_sc", "Standard Opponent 33 (Speed Challenge)" },
    { "opp_34_sc", "Standard Opponent 34 (Speed Challenge)" },
    { "opp_4_sc", "Standard Opponent 4 (Speed Challenge)" },
    { "opp_41_sc", "Standard Opponent 41 (Speed Challenge)" },
    { "opp_42_sc", "Standard Opponent 42 (Speed Challenge)" },
    { "opp_43_sc", "Standard Opponent 43 (Speed Challenge)" },
    { "opp_44_sc", "Standard Opponent 44 (Speed Challenge)" },
    { "opp_45_sc", "Standard Opponent 45 (Speed Challenge)" },
    { "opp_46_sc", "Standard Opponent 46 (Speed Challenge)" },
    { "opp_47_sc", "Standard Opponent 47 (Speed Challenge)" },
    { "opp_48_sc", "Standard Opponent 48 (Speed Challenge)" },
    { "opp_49_sc", "Standard Opponent 49 (Speed Challenge)" },
    { "opp_5_sc", "Standard Opponent 5 (Speed Challenge)" },
    { "opp_50_sc", "Standard Opponent 50 (Speed Challenge)" },
    { "opp_51_sc", "Standard Opponent 51 (Speed Challenge)" },
    { "opp_52_sc", "Standard Opponent 52 (Speed Challenge)" },
    { "opp_53_sc", "Standard Opponent 53 (Speed Challenge)" },
    { "opp_54_sc", "Standard Opponent 54 (Speed Challenge)" },
    { "opp_6_sc", "Standard Opponent 6 (Speed Challenge)" },
    { "opp_7_sc", "Standard Opponent 7 (Speed Challenge)" },
    { "opp_8_sc", "Standard Opponent 8 (Speed Challenge)" },
    { "opp_9_sc", "Standard Opponent 9 (Speed Challenge)" },

    // Player Specific Presets
    { "player_ch_t1_ptl_grip_civichb", "gti" },
    { "player_ch_t1_ptl_grip_mustgt", "mustanggt" },
    { "player_d_day", "240sx" },

    // Screenshot Vehicles
    { "screenshot_240sx_grip_1", "240sx" },
    { "screenshot_911t_grip_1", "997tt_highend" },
    { "screenshot_ae86_grip_1", "corolla_highendscgrip" },
    { "screenshot_corvette_grip_1", "0xdeaab3f1" },
    { "screenshot_cuda_grip_1", "cuda_track" },
    { "screenshot_elise_grip_1", "elise_track" },
    { "screenshot_g35_grip_1", "g35_highendscgrip" },
    { "screenshot_gt500_grip_1", " mustangshlbyn_highendscgrip" },
    { "screenshot_is350_grip_1", "is350_highendscgrip" },
    { "screenshot_kobel_s15_grip_1", "silvia_highendscgrip" },
    { "screenshot_mustang_grip_1", " mustanggt_highendscgrip" },
    { "screenshot_rsx_grip_1", " rsx_track_highend" },
    { "screenshot_rx7_grip_1", "rx7_highend" },
    { "screenshot_rx8_grip_1", "rx8_highendscgrip" },
    { "screenshot_s15_grip_1", "silvia_highendscgrip" },
    { "screenshot_skyline_grip_1", "skyline_highendscgrip" },
    { "screenshot_supra_grip_1", "supra_highendscgrip" },

    // Web Tool Cars
    { "webtool_focus_1", "focusst" },
    { "webtool_focus_2", "focusst" },
    { "webtool_focus_3", "focusst" },
    { "webtool_rsx_1", "rsx" },
    { "webtool_rsx_2", "rsx" },
    { "webtool_rsx_3", "rsx" },
    { "webtool_sti_1", "imprezawrxsti" },
    { "webtool_sti_2", "imprezawrxsti" },
    { "webtool_sti_3", "imprezawrxsti" },
    { "webtool_ttn_1", "ttn" },
    { "webtool_ttn_2", "ttn" },
    { "webtool_ttn_3", "ttn" }
};

        /*
        string[] presets = new string[]
{
    //temp_for_challenge
    "ch_t3_inf_drag",
    "ch_t3_inf_drift",
    "ch_t3_inf_grip",
    "ch_t3_inf_grip2",
    "p_ch_t1_nvd_drag",
    "p_ch_t1_nvd_drag2",
    "p_ch_t1_nvd_grip",
    "p_ch_t1_tx_drag",
    "p_ch_t1_tx_drift",
    "p_ch_t1_tx_grip",
    "p_ch_t1_tx_grip2",
    "p_ch_t1_willow_drag",
    "p_ch_t1_willow_drag2",
    "p_ch_t1_willow_drift",
    "p_ch_t1_willow_grip",
    "p_ch_t2_autop_drift",
    "p_ch_t2_autop_drift2",
    "p_ch_t2_autop_grip",
    "p_ch_t2_ce_autop_drift",
    "p_ch_t2_ce_autop_grip",
    "p_ch_t2_ce_autop_grip2",
    "p_ch_t2_eb_drift",
    "p_ch_t2_eb_grip",
    "p_ch_t2_eb_sc",
    "p_ch_t2_eb_sc2",
    "p_ch_t3_autob_drift",
    "p_ch_t3_autob_grip",
    "p_ch_t3_autob_sc",
    "p_ch_t3_autob_sc2",
    "p_ch_t3_nev_drag",
    "p_ch_t3_nev_drift",
    "p_ch_t3_nev_grip",
    "p_ch_t3_nev_sc",
    "p_ch_t3_nev_sc2",
    //ad sale
    "coke_gti",
    "energizer_viper",
    //bonus cars
    //0x2ea1c400 is a preset ride with no name
    "fe_drag_1_civichb",
    "fe_drag_1_cobaltss",
    "fe_drag_1_cuda",
    "fe_drag_1_mustshlbyo",
    "fe_drag_2_charg69",
    "fe_drag_2_eclipse",
    "fe_drag_2_evo09",
    "fe_drag_2_r32",
    "fe_drag_3_gti",
    "fe_drag_3_mustgt",
    "fe_drag_3_skyline",
    "fe_drag_3_wrx",
    "fe_drift_1_240sx",
    "fe_drift_1_corolla",
    "fe_drift_1_rx7",
    "fe_drift_1_silvia",
    "fe_drift_2_350z",
    "fe_drift_2_chevelle",
    "fe_drift_2_g35",
    "fe_drift_2_supra",
    "fe_drift_3_c6",
    "fe_drift_3_challenger",
    "fe_drift_3_rx8",
    "fe_drift_3_viper",
    "fe_grip_1_charger69",
    "fe_grip_1_chevelle",
    "fe_grip_1_corolla",
    "fe_grip_1_rx8",
    "fe_grip_2_cosworth",
    "fe_grip_2_eclipse",
    "fe_grip_2_g35",
    "fe_grip_2_s3",
    "fe_grip_3_corvc6",
    "fe_grip_3_gto",
    "fe_grip_3_murc640",
    "fe_grip_3_supra",
    "fe_sc_1_chall71",
    "fe_sc_1_cosworth",
    "fe_sc_1_r32",
    "fe_sc_1_s3",
    "fe_sc_2_elise",
    "fe_sc_2_rx8",
    "fe_sc_2_silvia",
    "fe_sc_3_camaross",
    "fe_sc_3_caymans",
    "fe_sc_3_fordgt",
    "fe_sc_3_s4",
    //booster opponents
    // b_opp_drag
    "b_opp_1_drag",
    "b_opp_10_drag",
    "b_opp_12_drag",
    "b_opp_14_drag",
    "b_opp_16_drag",
    "b_opp_18_drag",
    "b_opp_19_drag",
    "b_opp_2_drag",
    "b_opp_20_drag",
    "b_opp_21_drag",
    "b_opp_22_drag",
    "b_opp_3_drag",
    "b_opp_4_drag",
    "b_opp_5_drag",
    "b_opp_6_drag",
    "b_opp_7_drag",
    "b_opp_8_drag",
    "b_opp_9_drag",

    // b_opp_drift
    "b_opp_1_drift",
    "b_opp_10_drift",
    "b_opp_12_drift",
    "b_opp_14_drift",
    "b_opp_16_drift",
    "b_opp_18_drift",
    "b_opp_19_drift",
    "b_opp_2_drift",
    "b_opp_20_drift",
    "b_opp_21_drift",
    "b_opp_22_drift",
    "b_opp_3_drift",
    "b_opp_4_drift",
    "b_opp_5_drift",
    "b_opp_6_drift",
    "b_opp_7_drift",
    "b_opp_8_drift",
    "b_opp_9_drift",

    // b_opp_grip
    "b_opp_1_grip",
    "b_opp_10_grip",
    "b_opp_12_grip",
    "b_opp_14_grip",
    "b_opp_16_grip",
    "b_opp_18_grip",
    "b_opp_19_grip",
    "b_opp_2_grip",
    "b_opp_20_grip",
    "b_opp_21_grip",
    "b_opp_22_grip",
    "b_opp_3_grip",
    "b_opp_4_grip",
    "b_opp_5_grip",
    "b_opp_6_grip",
    "b_opp_7_grip",
    "b_opp_8_grip",
    "b_opp_9_grip",

    // b_opp_sc
    "b_opp_1_sc",
    "b_opp_10_sc",
    "b_opp_12_sc",
    "b_opp_14_sc",
    "b_opp_16_sc",
    "b_opp_18_sc",
    "b_opp_19_sc",
    "b_opp_2_sc",
    "b_opp_20_sc",
    "b_opp_21_sc",
    "b_opp_22_sc",
    "b_opp_3_sc",
    "b_opp_4_sc",
    "b_opp_5_sc",
    "b_opp_6_sc",
    "b_opp_7_sc",
    "b_opp_8_sc",
    "b_opp_9_sc",
    //commersial
    "commercial_ae86",
    "commercial_camaro",
    "commercial_cuda",
    "commercial_e92",
    "commercial_evo",
    "commercial_fordgt",
    "commercial_gt2",
    "commercial_mustang",
    "commercial_mustang_old",
    "commercial_proto",
    "commercial_rx7",
    "commercial_s15",
    "commercial_s4",
    "commercial_wrx",
    // debug_presets
    "jacques_mobile",
    "jacques_mobile_drag",
    "jacques_mobile_grip",
    "jacques_mobile_speed",

    // entourage_drag
    "drag_entourage_1_drag",
    "drag_entourage_2_drag",
    "drag_entourage_3_drag",
    "showdown_entourage_1_drag",
    "showdown_entourage_2_drag",
    "showdown_entourage_3_drag",
    "showdown_entourage_4_drag",

    // entourage_drift
    "drift_entourage_1_drift",
    "drift_entourage_2_drift",
    "drift_entourage_3_drift",
    "showdown_entourage_2_drift",

    // entourage_grip
    "grip_entourage_1_grip",
    "grip_entourage_2_grip",
    "grip_entourage_3_grip",
    "showdown_entourage_1_grip",
    "showdown_entourage_2_grip",
    "showdown_entourage_3_grip",
    "showdown_entourage_4_grip",

    // entourage_sc
    "sc_entourage_1_sc",
    "sc_entourage_2_sc",
    "sc_entourage_3_sc",
    "showdown_entourage_1_sc",
    "showdown_entourage_2_sc",
    "showdown_entourage_3_sc",
    "showdown_entourage_4_sc",

    // king
    "drag_king",
    "drift_king",
    "grip_king",
    "sc_king",
    "showdown_king_final_drag",
    "showdown_king_final_drift",
    "showdown_king_final_grip",
    "showdown_king_final_sc",
    "showdown_king_playable",


    // challenge_drag
    "ch_t1_ptl_drag_civichb",
    "ch_t1_ptl_drag_mustgt",
    "ch_t1_tx_drag_gti",
    "ch_t1_willow_drag_chevelle",
    "ch_t3_infineon_drag_cayman",
    "ch_t3_nevada_drag_z06",

    // challenge_drift
    "ch_t1_tx_drift_350z",
    "ch_t1_willow_drift_chevelle",
    "ch_t1_willow_drift_is350",
    "ch_t2_autop_drift_s15",
    "ch_t2_autop_drift_solstice",
    "ch_t2_ebisu_drift_supra",
    "ch_t2_mond_drift_g35",
    "ch_t2_mond_drift_gto",
    "ch_t3_autob_drift_viper",
    "ch_t3_infineon_drift_nsx",
    "ch_t3_nevada_drift_z06",

    // challenge_grip
    "ch_t1_ptl_grip_civichb",
    "ch_t1_tx_grip_350z",
    "ch_t1_tx_grip_gti",
    "ch_t1_willow_grip_is350",
    "ch_t2_autop_grip_s15",
    "ch_t2_ebisu_grip_bmwm3",
    "ch_t2_mond_grip_gto",
    "ch_t3_autob_grip_skyline",
    "ch_t3_infineon_grip_cayman",
    "ch_t3_infineon_grip_nsx",
    "ch_t3_nevada_grip_rs4",

    // challenge_sc
    "ch_t2_ebisu_sc_bmwm3",
    "ch_t2_ebisu_sc_supra",
    "ch_t3_autob_sc_skyline",
    "ch_t3_autob_sc_viper",
    "ch_t3_nevada_sc_rs4",
    "ch_t3_nevada_sc_z06",

    // dday_grip
    "dday_opp_1_grip",
    "dday_opp_2_grip",
    "dday_opp_3_grip",
    "dday_opp_4_grip",
    "dday_opp_5_grip",
    "dday_opp_6_grip",
    "dday_opp_7_grip",

    // elite_drag
    "elite_opp_1_drag",
    "elite_opp_11_drag",
    "elite_opp_12_drag",
    "elite_opp_13_drag",
    "elite_opp_14_drag",
    "elite_opp_15_drag",
    "elite_opp_16_drag",
    "elite_opp_17_drag",
    "elite_opp_18_drag",
    "elite_opp_19_drag",
    "elite_opp_2_drag",
    "elite_opp_20_drag",
    "elite_opp_21_drag",
    "elite_opp_22_drag",
    "elite_opp_23_drag",
    "elite_opp_24_drag",
    "elite_opp_25_drag",
    "elite_opp_26_drag",
    "elite_opp_3_drag",
    "elite_opp_4_drag",
    "elite_opp_5_drag",

    // elite_drift
    "elite_opp_1_drift",
    "elite_opp_11_drift",
    "elite_opp_12_drift",
    "elite_opp_13_drift",
    "elite_opp_14_drift",
    "elite_opp_15_drift",
    "elite_opp_16_drift",
    "elite_opp_17_drift",
    "elite_opp_18_drift",
    "elite_opp_19_drift",
    "elite_opp_2_drift",
    "elite_opp_20_drift",
    "elite_opp_3_drift",
    "elite_opp_4_drift",
    "elite_opp_5_drift",

    // elite_grip
    "elite_opp_1_grip",
    "elite_opp_11_grip",
    "elite_opp_12_grip",
    "elite_opp_13_grip",
    "elite_opp_14_grip",
    "elite_opp_15_grip",
    "elite_opp_16_grip",
    "elite_opp_17_grip",
    "elite_opp_18_grip",
    "elite_opp_19_grip",
    "elite_opp_2_grip",
    "elite_opp_20_grip",
    "elite_opp_27_grip",
    "elite_opp_3_grip",
    "elite_opp_4_grip",
    "elite_opp_5_grip",
    // elite_sc
    "elite_opp_14_sc",
    "elite_opp_15_sc",
    "elite_opp_16_sc",
    "elite_opp_17_sc",
    "elite_opp_18_sc",
    "elite_opp_19_sc",
    "elite_opp_2_sc",
    "elite_opp_20_sc",
    "elite_opp_3_sc",
    "elite_opp_4_sc",
    "elite_opp_5_sc",

    // hd_drag
    "hd_opp_1_drag",
    "hd_opp_10_drag",
    "hd_opp_11_drag",
    "hd_opp_12_drag",
    "hd_opp_13_drag",
    "hd_opp_14_drag",
    "hd_opp_15_drag",
    "hd_opp_2_drag",
    "hd_opp_3_drag",
    "hd_opp_4_drag",
    "hd_opp_5_drag",
    "hd_opp_6_drag",
    "hd_opp_7_drag",
    "hd_opp_8_drag",
    "hd_opp_9_drag",

    // hd_drift
    "hd_opp_1_drift",
    "hd_opp_10_drift",
    "hd_opp_11_drift",
    "hd_opp_12_drift",
    "hd_opp_13_drift",
    "hd_opp_14_drift",
    "hd_opp_15_drift",
    "hd_opp_2_drift",
    "hd_opp_3_drift",
    "hd_opp_4_drift",
    "hd_opp_5_drift",
    "hd_opp_6_drift",
    "hd_opp_7_drift",
    "hd_opp_8_drift",
    "hd_opp_9_drift",

    // hd_grip
    "hd_opp_1_grip",
    "hd_opp_10_grip",
    "hd_opp_11_grip",
    "hd_opp_12_grip",
    "hd_opp_13_grip",
    "hd_opp_14_grip",
    "hd_opp_15_grip",
    "hd_opp_2_grip",
    "hd_opp_3_grip",
    "hd_opp_4_grip",
    "hd_opp_5_grip",
    "hd_opp_6_grip",
    "hd_opp_7_grip",
    "hd_opp_8_grip",
    "hd_opp_9_grip",

    // hd_sc
    "hd_opp_1_sc",
    "hd_opp_10_sc",
    "hd_opp_11_sc",
    "hd_opp_12_sc",
    "hd_opp_13_sc",
    "hd_opp_14_sc",
    "hd_opp_15_sc",
    "hd_opp_2_sc",
    "hd_opp_3_sc",
    "hd_opp_4_sc",
    "hd_opp_5_sc",
    "hd_opp_6_sc",
    "hd_opp_7_sc",
    "hd_opp_8_sc",
    "hd_opp_9_sc",
    // opp_drag
    "opp_0_drag",
    "opp_1_drag",
    "opp_10_drag",
    "opp_11_drag",
    "opp_12_drag",
    "opp_13_drag",
    "opp_14_drag",
    "opp_2_drag",
    "opp_20_drag",
    "opp_21_drag",
    "opp_22_drag",
    "opp_23_drag",
    "opp_24_drag",
    "opp_25_drag",
    "opp_26_drag",
    "opp_27_drag",
    "opp_28_drag",
    "opp_29_drag",
    "opp_3_drag",
    "opp_30_drag",
    "opp_31_drag",
    "opp_32_drag",
    "opp_33_drag",
    "opp_34_drag",
    "opp_4_drag",
    "opp_41_drag",
    "opp_42_drag",
    "opp_43_drag",
    "opp_44_drag",
    "opp_45_drag",
    "opp_46_drag",
    "opp_47_drag",
    "opp_48_drag",
    "opp_49_drag",
    "opp_5_drag",
    "opp_50_drag",
    "opp_51_drag",
    "opp_52_drag",
    "opp_53_drag",
    "opp_54_drag",
    "opp_6_drag",
    "opp_7_drag",
    "opp_8_drag",
    "opp_9_drag",

    // opp_drift
    "opp_0_drift",
    "opp_1_drift",
    "opp_10_drift",
    "opp_11_drift",
    "opp_12_drift",
    "opp_13_drift",
    "opp_14_drift",
    "opp_2_drift",
    "opp_20_drift",
    "opp_21_drift",
    "opp_22_drift",
    "opp_23_drift",
    "opp_24_drift",
    "opp_25_drift",
    "opp_26_drift",
    "opp_27_drift",
    "opp_28_drift",
    "opp_29_drift",
    "opp_3_drift",
    "opp_30_drift",
    "opp_31_drift",
    "opp_32_drift",
    "opp_33_drift",
    "opp_34_drift",
    "opp_4_drift",
    "opp_41_drift",
    "opp_42_drift",
    "opp_43_drift",
    "opp_44_drift",
    "opp_45_drift",
    "opp_46_drift",
    "opp_47_drift",
    "opp_48_drift",
    "opp_49_drift",
    "opp_5_drift",
    "opp_50_drift",
    "opp_51_drift",
    "opp_52_drift",
    "opp_53_drift",
    "opp_54_drift",
    "opp_6_drift",
    "opp_7_drift",
    "opp_8_drift",
    "opp_9_drift",

    // opp_grip
    "opp_0_grip",
    "opp_1_grip",
    "opp_10_grip",
    "opp_11_grip",
    "opp_12_grip",
    "opp_13_grip",
    "opp_14_grip",
    "opp_2_grip",
    "opp_20_grip",
    "opp_21_grip",
    "opp_22_grip",
    "opp_23_grip",
    "opp_24_grip",
    "opp_25_grip",
    "opp_26_grip",
    "opp_27_grip",
    "opp_28_grip",
    "opp_29_grip",
    "opp_3_grip",
    "opp_30_grip",
    "opp_31_grip",
    "opp_32_grip",
    "opp_33_grip",
    "opp_34_grip",
    "opp_4_grip",
    "opp_41_grip",
    "opp_42_grip",
    "opp_43_grip",
    "opp_44_grip",
    "opp_45_grip",
    "opp_46_grip",
    "opp_47_grip",
    "opp_48_grip",
    "opp_49_grip",
    "opp_5_grip",
    "opp_50_grip",
    "opp_51_grip",
    "opp_52_grip",
    "opp_53_grip",
    "opp_54_grip",
    "opp_6_grip",
    "opp_7_grip",
    "opp_8_grip",
    "opp_9_grip",

    // opp_sc
    "opp_0_sc",
    "opp_1_sc",
    "opp_10_sc",
    "opp_11_sc",
    "opp_12_sc",
    "opp_13_sc",
    "opp_14_sc",
    "opp_2_sc",
    "opp_20_sc",
    "opp_21_sc",
    "opp_22_sc",
    "opp_23_sc",
    "opp_24_sc",
    "opp_25_sc",
    "opp_26_sc",
    "opp_27_sc",
    "opp_28_sc",
    "opp_29_sc",
    "opp_3_sc",
    "opp_30_sc",
    "opp_31_sc",
    "opp_32_sc",
    "opp_33_sc",
    "opp_34_sc",
    "opp_4_sc",
    "opp_41_sc",
    "opp_42_sc",
    "opp_43_sc",
    "opp_44_sc",
    "opp_45_sc",
    "opp_46_sc",
    "opp_47_sc",
    "opp_48_sc",
    "opp_49_sc",
    "opp_5_sc",
    "opp_50_sc",
    "opp_51_sc",
    "opp_52_sc",
    "opp_53_sc",
    "opp_54_sc",
    "opp_6_sc",
    "opp_7_sc",
    "opp_8_sc",
    "opp_9_sc",
    // player_presets
    "player_ch_t1_ptl_grip_civichb",
    "player_ch_t1_ptl_grip_mustgt",
    "player_d_day",

    // screenshots
    "screenshot_240sx_grip_1",
    "screenshot_911t_grip_1",
    "screenshot_ae86_grip_1",
    "screenshot_corvette_grip_1",
    "screenshot_cuda_grip_1",
    "screenshot_elise_grip_1",
    "screenshot_g35_grip_1",
    "screenshot_gt500_grip_1",
    "screenshot_is350_grip_1",
    "screenshot_kobel_s15_grip_1",
    "screenshot_mustang_grip_1",
    "screenshot_rsx_grip_1",
    "screenshot_rx7_grip_1",
    "screenshot_rx8_grip_1",
    "screenshot_s15_grip_1",
    "screenshot_skyline_grip_1",
    "screenshot_supra_grip_1",

    // webtool
    "webtool_focus_1",
    "webtool_focus_2",
    "webtool_focus_3",
    "webtool_rsx_1",
    "webtool_rsx_2",
    "webtool_rsx_3",
    "webtool_sti_1",
    "webtool_sti_2",
    "webtool_sti_3",
    "webtool_ttn_1",
    "webtool_ttn_2",
    "webtool_ttn_3"
}; */
    }
}
